spring.application.name=catalogo_carrinho_api
spring.profiles.active=${APP_PROFILE:dev}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html